
package org.smartlabs.core.cmis.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-03-01T13:47:37.890-04:30
 * Generated source version: 2.7.4
 */

@WebFault(name = "cmisFault", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
public class CmisException extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -3566916970133215637L;
	private org.smartlabs.core.cmis.messaging.CmisFaultType cmisFault;

    public CmisException() {
        super();
    }
    
    public CmisException(String message) {
        super(message);
    }
    
    public CmisException(String message, Throwable cause) {
        super(message, cause);
    }

    public CmisException(String message, org.smartlabs.core.cmis.messaging.CmisFaultType cmisFault) {
        super(message);
        this.cmisFault = cmisFault;
    }

    public CmisException(String message, org.smartlabs.core.cmis.messaging.CmisFaultType cmisFault, Throwable cause) {
        super(message, cause);
        this.cmisFault = cmisFault;
    }

    public org.smartlabs.core.cmis.messaging.CmisFaultType getFaultInfo() {
        return this.cmisFault;
    }
}
