package org.smartlabs.core.cmis.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-03-01T13:47:37.975-04:30
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", name = "NavigationServicePort")
@XmlSeeAlso({org.smartlabs.core.cmis.core.ObjectFactory.class, org.smartlabs.core.cmis.messaging.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NavigationServicePort {

    @WebResult(name = "getCheckedOutDocsResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetCheckedOutDocsResponse getCheckedOutDocs(
        @WebParam(partName = "parameters", name = "getCheckedOutDocs", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetCheckedOutDocs parameters
    ) throws CmisException;

    @WebResult(name = "getObjectParentsResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetObjectParentsResponse getObjectParents(
        @WebParam(partName = "parameters", name = "getObjectParents", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetObjectParents parameters
    ) throws CmisException;

    @WebResult(name = "getDescendantsResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetDescendantsResponse getDescendants(
        @WebParam(partName = "parameters", name = "getDescendants", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetDescendants parameters
    ) throws CmisException;

    @WebResult(name = "getChildrenResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetChildrenResponse getChildren(
        @WebParam(partName = "parameters", name = "getChildren", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetChildren parameters
    ) throws CmisException;

    @WebResult(name = "getFolderTreeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetFolderTreeResponse getFolderTree(
        @WebParam(partName = "parameters", name = "getFolderTree", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetFolderTree parameters
    ) throws CmisException;

    @WebResult(name = "getFolderParentResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetFolderParentResponse getFolderParent(
        @WebParam(partName = "parameters", name = "getFolderParent", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetFolderParent parameters
    ) throws CmisException;
}
