package org.smartlabs.core.cmis.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-03-01T13:47:38.343-04:30
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "RelationshipService", 
                  wsdlLocation = "https://cmis.alfresco.com/cmisws/NavigationService?wsdl",
                  targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/") 
public class RelationshipService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "RelationshipService");
    public final static QName RelationshipServicePort = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "RelationshipServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://cmis.alfresco.com/cmisws/NavigationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RelationshipService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://cmis.alfresco.com/cmisws/NavigationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RelationshipService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RelationshipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RelationshipService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RelationshipServicePort
     */
    @WebEndpoint(name = "RelationshipServicePort")
    public RelationshipServicePort getRelationshipServicePort() {
        return super.getPort(RelationshipServicePort, RelationshipServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RelationshipServicePort
     */
    @WebEndpoint(name = "RelationshipServicePort")
    public RelationshipServicePort getRelationshipServicePort(WebServiceFeature... features) {
        return super.getPort(RelationshipServicePort, RelationshipServicePort.class, features);
    }

}
