package org.smartlabs.core.cmis.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-03-01T13:47:38.152-04:30
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", name = "RepositoryServicePort")
@XmlSeeAlso({org.smartlabs.core.cmis.core.ObjectFactory.class, org.smartlabs.core.cmis.messaging.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RepositoryServicePort {

    @WebResult(name = "getTypeChildrenResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetTypeChildrenResponse getTypeChildren(
        @WebParam(partName = "parameters", name = "getTypeChildren", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetTypeChildren parameters
    ) throws CmisException;

    @WebResult(name = "getRepositoryInfoResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetRepositoryInfoResponse getRepositoryInfo(
        @WebParam(partName = "parameters", name = "getRepositoryInfo", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetRepositoryInfo parameters
    ) throws CmisException;

    @WebResult(name = "getTypeDefinitionResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetTypeDefinitionResponse getTypeDefinition(
        @WebParam(partName = "parameters", name = "getTypeDefinition", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetTypeDefinition parameters
    ) throws CmisException;

    @WebResult(name = "getTypeDescendantsResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetTypeDescendantsResponse getTypeDescendants(
        @WebParam(partName = "parameters", name = "getTypeDescendants", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetTypeDescendants parameters
    ) throws CmisException;

    @WebResult(name = "getRepositoriesResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", partName = "parameters")
    @WebMethod
    public org.smartlabs.core.cmis.messaging.GetRepositoriesResponse getRepositories(
        @WebParam(partName = "parameters", name = "getRepositories", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        org.smartlabs.core.cmis.messaging.GetRepositories parameters
    ) throws CmisException;
}
